// Generated by GenerateAst.py

#ifndef Stmt_h
#define Stmt_h
#include "Token.h"


class Expression;
class Print;
class Stmt
{
public:

    class Visitor
    {
    public:
        virtual void visit(Expression& el)=0;
        virtual void visit(Print& el)=0;
    };

    virtual void accept(Visitor& v) = 0;
};

class Expression : public Stmt
{
public:
    Expression(std::shared_ptr<Expr> expression):expression{expression}{}

   void accept(Visitor& v) override
    {
        return v.visit(*this);
    }

    std::shared_ptr<Expr> expression;

};

class Print : public Stmt
{
public:
    Print(std::shared_ptr<Expr> expression):expression{expression}{}

   void accept(Visitor& v) override
    {
        return v.visit(*this);
    }

    std::shared_ptr<Expr> expression;

};

#endif
